### ISSUE TITLE
Retry policy with backoff doesn't add backoff

### ISSUE THREAD

**Issue by eranharel** [failsafe-go/failsafe-go#23]
I think it's because `retrypolicy/retryexecutor.go:132` looks at `config.maxDelay` instead of `config.delayMax`, and the former seems to be a leftover just field

**Comment by jhalterman** [comment]
Thanks for filing this. It should be fixed via 9b9ce14c0cb2b2c479bfe0918b5eb6720a9cbbdc and will be released in 0.4.2 today.

**Comment by jhalterman** [comment]
This has been released in 0.4.2.

**Comment by eranharel** [comment]
Thanks for the prompt fix @jhalterman \m/,

**Comment by eranharel** [comment]
Verified your fix, thanks
