### ISSUE TITLE
Dual License

### ISSUE THREAD

**Issue by gaby** [failsafe-go/failsafe-go#35]
@jhalterman What are your thoughts on making the project Dual License by adding MIT license? 

A lot of the Go modules are MIT, and the license on this one conflicts with that.

**Comment by jhalterman** [comment]
I'd be fine with just changing the license to MIT, if that works?

**Comment by gaby** [comment]
@jhalterman Yes, that works too. The dual license is something used a lot in Rust projects since it allows you to apply one or the other based on your project.

**Comment by gaby** [comment]
For example: https://github.com/actix/actix-web

**Comment by gaby** [comment]
@jhalterman Submitted PR to fix this issue #41
