### ISSUE TITLE
Add gRPC support

### ISSUE THREAD

**Issue by jhalterman** [failsafe-go/failsafe-go#37]
Add gRPC support as a middleware, similar to the RoundTripper based HTTP support.

**Comment by szabba** [comment]
This should actually work with the gRPC-compattible [connect-go] already.

[connect-go]: https://github.com/connectrpc/connect-go

**Comment by proost** [comment]
I need this feature. could i contribute this?

**Comment by jhalterman** [comment]
Sure - I could review a contribution for this. The [failsafehttp package](https://failsafe-go.dev/http/) allows you to create either a Failsafe RoundTripper, or a Failsafe Request. It also has a `RetryPolicyBuilder` for building retry policies with built in handling for common response codes.

I don't have any ideas yet for what a failsafegrpc package might look like, but I'm interested to hear what you think.

**Comment by proost** [comment]
I plan to use `UnaryClientInterceptor` and `StreamClientInterceptor`. 

Same as `failsafehttp`, supporting `RetryPolicyBuilder` to handle common retryable grpc status code(ex. DEADLINE_EXCEEDED, UNAVAILABLE) is good.

**Comment by jhalterman** [comment]
That's sounds good. On the server side, we should also allow creating a failsafe tap handle (used via `grpc.InTapHandle`) that could be used for things like server side circuit breakers or rate limiters.
