### ISSUE TITLE
Add caching support 

### ISSUE THREAD

**Issue by sazzer** [failsafe-go/failsafe-go#38]
I'm not sure if this really fits in with the goals for this library, but one potential new policy that could be useful is one that supports caching.

This would then allow for successful results to be cached for a period, and those values get returned instead of calling downstream. That in turn helps take load off other services when results can be cached.

**Comment by jhalterman** [comment]
Hey Graham - I think a cache would be a good fit, as it can limit load. I don't mind adding this. Do you have any thoughts on how it might or should work?

**Comment by jhalterman** [comment]
@sazzer - I sketched out an implementation and pushed it to #44. Let me know what you think.
