### ISSUE TITLE
Feature: snapshot of current stats when change to "closed" to "open"

### ISSUE THREAD

**Issue by proost** [failsafe-go/failsafe-go#57]
I use "openListener" to logging and sending alert. 

When circuitbreaker state change from "closed" to "open", current stats of circuit breaker can be more helpful for debugging and custom alerting. 

Adding stats to "StateChangedEvent" can solve this. how do you think about this?

**Comment by jhalterman** [comment]
Is this what you had in mind - adding Metrics() to StateChangedEvent?

52f256c9f37f789e676401e8ebfee01ca14b96cc

Let me know, and I can merge into main for the next release.

**Comment by proost** [comment]
@jhalterman 
Yes, right.

Thank you!
